/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9storybook;

/**
 *
 * @author Shashank Mondrati
 * @version 12/3/2020
 */
public class EndFrame extends javax.swing.JFrame {

    private StorybookModel myModel;
   

    /**
     * Creates new form EndFrame
     *
     */
    public EndFrame(StorybookModel model) {
        initComponents();
        this.myModel = model;
        welcomeLabel1.setText("Welcome, " + myModel.getUserName() + " .");
        crimeLabel.setText("You have been accused of " + myModel.getCrime());
        instructionLabel1.setVisible(true);
    }

    EndFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel1 = new javax.swing.JLabel();
        crimeLabel = new javax.swing.JLabel();
        instructionLabel1 = new javax.swing.JLabel();
        rightDoorButton = new javax.swing.JButton();
        leftDoorButton = new javax.swing.JButton();
        nextTrial = new javax.swing.JButton();
        exitTrial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        welcomeLabel1.setText("Welcome");

        crimeLabel.setText("You have been accused of");

        instructionLabel1.setText("Pick a door to choose your verdict ");

        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF"))); // NOI18N
        rightDoorButton.setBorderPainted(false);
        rightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorButtonActionPerformed(evt);
            }
        });

        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF"))); // NOI18N
        leftDoorButton.setText("You are Guilty Prepare to be Eaten!!!");
        leftDoorButton.setBorderPainted(false);
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });

        nextTrial.setText("Next Trial");
        nextTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTrialActionPerformed(evt);
            }
        });

        exitTrial.setText("Exit Tribunal");
        exitTrial.setEnabled(false);
        exitTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTrialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(instructionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(exitTrial)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(nextTrial))
                            .addComponent(rightDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(938, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightDoorButton)
                    .addComponent(leftDoorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextTrial)
                    .addComponent(exitTrial))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed

        instructionLabel1.setText("You are GUILTY! Prepare to be eaten!");
        rightDoorButton.setVisible(false);
        exitTrial.setEnabled(true);
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Tiger.GIF")));
    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void rightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorButtonActionPerformed

        instructionLabel1.setText("You are INNOCENT! Sorry about that. Please accept this lady");
        leftDoorButton.setVisible(false);
        nextTrial.setEnabled(true);
        exitTrial.setEnabled(true);
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Lady.GIF")));
    }//GEN-LAST:event_rightDoorButtonActionPerformed

    private void exitTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTrialActionPerformed

        System.exit(0);
    }//GEN-LAST:event_exitTrialActionPerformed

    private void nextTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialActionPerformed
      dispose();
        StartFrame sf = new StartFrame(myModel);
        sf.setVisible(true);
    }//GEN-LAST:event_nextTrialActionPerformed
   
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crimeLabel;
    private javax.swing.JButton exitTrial;
    private javax.swing.JLabel instructionLabel1;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JButton nextTrial;
    private javax.swing.JButton rightDoorButton;
    private javax.swing.JLabel welcomeLabel1;
    // End of variables declaration//GEN-END:variables

}
